# Peripheral half: deep sleep; wake on keypress.
CONFIG_ZMK_SLEEP=y

# MCU status LED battery blink on boot.
CONFIG_INDICATOR_LED_WIDGET=y
CONFIG_INDICATOR_LED_SHOW_BATTERY_ON_BOOT=y
CONFIG_INDICATOR_LED_SHOW_LAYER_CHANGE=n
CONFIG_INDICATOR_LED_SHOW_BLE=n
